# list of labels and minimatch globs to match to apply the label.
# for more information see:
# https://github.com/actions/labeler

# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'enhancement' label to any change to files within the Part-1,Part-2 & ISSUE_TEMPLATE dir
enhancement:
- 'Part-1/*'
- 'Part-2/*'
- '.github/ISSUE_TEMPLATE/*.md'

# Add 'part1' label to any change to *.c files within the Part-1 dir
part1:
- 'Part-1/*.c'

# Add 'part2' label to any change to *.c files within the Part-2 dir
part2:
- 'Part-2/*.c'

# Add 'documentation' label to any change to README.md file.
documentation:
- README.md
- CONTRIBUTING.md

# Add 'workflow' label to any change to files within the workflow dir
workflow:
- '.github/workflows/*'
