# list of labels and minimatch globs to match to apply the label.
# for more information see: 
# https://github.com/actions/labeler 

# Add 'enhancement' label to any root file changes
enhancement:
- '*'

# Add 'part1' label to any change to *.c files within the Part-1 dir
part1:
- 'Part-1/*.c'

# Add 'part2' label to any change to *.c files within the Part-2 dir
part2:
- 'Part-2/*.c'

# Add 'documentation' label to any change to README.md file .
documentation:
- README.md 
  
